blank_issues_enabled: false
contact_links:
- name: Discussion board
  url: https://github.com/pypsa-meets-earth/pypsa-earth/discussions
  about: Please ask and answer general usage questions here.
